// Copyright 2018-2024 contributors to the Marquez project
// SPDX-License-Identifier: Apache-2.0

export const APPLICATION_ERROR = 'APPLICATION_ERROR'
export const DIALOG_TOGGLE = 'DIALOG_TOGGLE'

export const FETCH_NAMESPACES_SUCCESS = 'FETCH_NAMESPACES_SUCCESS'
export const SELECT_NAMESPACE = 'SELECT_NAMESPACE'

export const SET_SELECTED_NODE = 'SET_SELECTED_NODE'

export const SET_BOTTOM_BAR_HEIGHT = 'SET_BOTTOM_BAR_HEIGHT'

export const SET_TAB_INDEX = 'SET_TAB_INDEX'

export const RESET_JOBS = 'RESET_JOBS'

// datasets
export const RESET_DATASETS = 'RESET_DATASETS'
export const RESET_DATASET = 'RESET_DATASET'
export const RESET_DATASET_VERSIONS = 'RESET_DATASET_VERSIONS'

export const FETCH_INITIAL_DATASET_VERSIONS = 'FETCH_INITIAL_DATASET_VERSIONS'
export const FETCH_INITIAL_DATASET_VERSIONS_SUCCESS = 'FETCH_INITIAL_DATASET_VERSIONS_SUCCESS'

// events
export const RESET_EVENTS = 'RESET_EVENTS'

// lineage
export const RESET_LINEAGE = 'RESET_LINEAGE'
export const SET_LINEAGE_GRAPH_DEPTH = 'SET_LINEAGE_GRAPH_DEPTH'
export const SET_SHOW_FULL_GRAPH = 'SET_SHOW_FULL_GRAPH'

// OpenSearch
export const FETCH_OPEN_SEARCH_JOBS = 'FETCH_OPEN_SEARCH_JOBS'
export const FETCH_OPEN_SEARCH_JOBS_SUCCESS = 'FETCH_OPEN_SEARCH_JOBS_SUCCESS'
export const FETCH_OPEN_SEARCH_DATASETS = 'FETCH_OPEN_SEARCH_DATASETS'
export const FETCH_OPEN_SEARCH_DATASETS_SUCCESS = 'FETCH_OPEN_SEARCH_DATASETS_SUCCESS'

// facets
export const RESET_FACETS = 'RESET_FACETS'

// tags
